### ISSUE TITLE
Multiple carbon-relay-ng and downstream aggregation

### ISSUE THREAD

**Issue by bwhaley** [graphite-ng/carbon-relay-ng#143]
Apologies if there is a better place for this - point me to the correct IRC channel or mailing list if such a thing exists.

I believe my question is straightforward: If you're running multiple carbon-relay-ngs for HA, and they're configured to do aggregations, then each of them is aggregating only a subset of the metrics. In my case, I intend to have an autoscaling group of them behind a load balancer. Is it expected to run carbon-aggregator.py in front of each carbon-cache.py daemon to average aggregates and achieve the final result?

Thanks in advance!

**Comment by Dieterbe** [comment]
> Is it expected to run carbon-aggregator.py in front of each carbon-cache.py daemon to average aggregates and achieve the final result?

no. you could run carbon-relay-ng in front of carbon-cache.py (and behind your loadbalanced carbon-relay-ng's) instead, but even this is rather ugly.

I think the best solution would be if you just routed metrics such that those that need to be aggregated together, go into the same carbon-relay-ng. then you don't need anything else.

**Comment by bwhaley** [comment]
That doesn't seem a very complete HA solution. What if we lose the host running carbon-relay-ng? 

I like the idea of running carbon-relay-ng in front of carbon-cache.py with a different aggregation config. Guess I will go that route (pun intended).

Thanks so much for your project and your prompt reply!

**Comment by Dieterbe** [comment]
> That doesn't seem a very complete HA solution. What if we lose the host running carbon-relay-ng?

then you reroute to another one.
of course, the solution i'm suggestion here would require you have some sort of loadbalancer that understands the carbon protocol and works on that level. (or a similar newline-based text protocol over tcp)
i'm not aware of anything like that existing..

**Comment by bwhaley** [comment]
HAProxy custom checks may be able to do this, e.g.

https://www.haproxy.com/doc/aloha/7.0/haproxy/healthchecks.html#checking-any-service

But we are using AWS ELB which does not support active/standby or weighted
load balancing.

So in my case I will use the solution previously discussed: ELB =>
Autoscaling group of carbon-relay-ng => carbon-relay-ng for final
aggregation in front of carbon-cache.py. It’s slightly kludgy but not
completely offensive.

Thanks!

**Comment by Dieterbe** [comment]
good luck :)

**Comment by bwhaley** [comment]
For posterity, I'll just state here that my plan did not work out at all. Running multiple carbon-relay-ngs, forwarding to a consistent hashing cluster of carbon-cache nodes with either carbon-relay-ng or carbon-aggregator.py in front of them caused a lot of data discrepancy issues. I could not get the timing right - no matter the configuration, there would always be some time periods with too much data and other periods with null values. When I remove the extra aggregation everything works fine.

To handle HA I'm just going to have self-healing/bootstrapping on the carbon-relay-ng. If the instance dies, we'll have at most a few minutes of downtime while a replacement boots. I may move carbon-relay-ng to a container to minimize this even further. 

Thanks again for sharing your thoughts @Dieterbe.

**Comment by guillaume-lin** [comment]
I also aggregate metric using this config. my concern is that with just one carbon-relay-ng here, we can not scale out. but if we use multi carbon-relay-ng, the aggregation is incorrect.

**Comment by Dieterbe** [comment]
> To handle HA I'm just going to have self-healing/bootstrapping on the carbon-relay-ng. If the instance dies, we'll have at most a few minutes of downtime while a replacement boots. I may move carbon-relay-ng to a container to minimize this even further.

this is also the route we're taking with carbon-relay-ng and many of our other things (e.g. also metrictank, which can replay from a kafka log, so in that case a crash and restart has 0 dropped data because it replays at start) . we use kubernetes for orchestration and run things in docker containers.

@bwhaley @guillaume-lin both of you mention incorrect aggregation output of the "final" / 2-nd tier aggregation and I wonder why. perhaps the wait parameter is not enough to cover variance amongst it inputs? i suggest you do some network sniffing and focus in on a specific series to find out.

also i realized you could do away with the need for failover as i mentioned earlier, but then you need full replication e.g. multiple relay instances each getting identical input and the same aggregation config, so they also output the same data, if one of them dies, no problem.. of course this is not very efficient and doesn't help with splitting load across instances.
