### ISSUE TITLE
badMetrics not displaying all metrics

### ISSUE THREAD

**Issue by MilosD** [graphite-ng/carbon-relay-ng#151]
Hey guys,

When accessing badMetrics route, only last received badMetrics is displayed. Example:
```
[

    {
        "Metric": "",
        "LastMsg": "foo.bar.baz.value [J@7b5d2a33 1484824598",
        "LastErr": "value field is not a float or int",
        "LastSeen": "2017-01-19T12:16:38.466662719+01:00"
    }

]
```
When page is refreshed, new bad metrics is displayed but previous one disappeared. Is this intended behavior? Is there a way to list all bad metrics?

Thanks,
Miloš

**Comment by isavcic** [comment]
Just to add, we have `bad_metrics_max_age` set to `24h`:

```
bad_metrics_max_age = "24h"
```

**Comment by isavcic** [comment]
Same thing with `90836096584c1278b4462fed3dfd09a13af1b5f6`.

**Comment by Dieterbe** [comment]
from memory, it should retain the last error per metric key, but seems from your output that it assigns the empty string as metric key to all errors, so they would overwrite each other.

that's what it looks like from first glance at least.

**Comment by isavcic** [comment]
Good point. This seems to be a bug in `metrics20/go-metrics20`. I believe it's safe to return `fields[0]` instead of `empty` [here](https://github.com/metrics20/go-metrics20/blob/master/carbon20/validate.go#L224), [here](https://github.com/metrics20/go-metrics20/blob/master/carbon20/validate.go#L229) and [here](https://github.com/metrics20/go-metrics20/blob/master/carbon20/validate.go#L234), since we have exactly three fields to work on (that check passed [here](https://github.com/metrics20/go-metrics20/blob/master/carbon20/validate.go#L210)).

**Comment by isavcic** [comment]
In other words, if we have three fields, we can call the first one "key"?
