### ISSUE TITLE
New aggregator: rate calculation aggregation

### ISSUE THREAD

**Issue by guillaumeautran** [graphite-ng/carbon-relay-ng#207]
We need an aggregator which is able to calculate a rate of change on a monotonic increasing serie (such as a counter). The rate calculation would take the `first` and `last` number in the reporting window and compute the difference (`last` - `first`). This difference is then divided by the delta time between those two values. A simple rate calculation could be:

Equation 1:
![image](https://user-images.githubusercontent.com/13353403/28829121-cb87f58e-76a0-11e7-870c-729dc36790d6.png)

If considering counter wrap around, a better formula could be: 

Equation 2:
![image](https://user-images.githubusercontent.com/13353403/28829209-04e7289a-76a1-11e7-9c4a-8ac38cbda4de.png)

(Source: [Collectd Data Source](https://collectd.org/wiki/index.php/Data_source))

**Comment by Dieterbe** [comment]
@guillaumeautran this sounds good and is what we need as well for the aggregation of our counters.

**Comment by guillaumeautran** [comment]
Awsome! I'll get to work on it sometimes this week hopefully.

Do you think the configuration should support disabling / enabling wrap-around support (equation 1 vs equation 2 respectively)?
My initial thought would be "no - we only support equation 2 " and we can revisit if there is a need to support equation 1. 
But I can be convinced either way...

**Comment by Dieterbe** [comment]
currently all the code assumes float64 data. so it currently does not support 64bit integer counters since those don't fit in float64.
so one question to solve is what datatypes we should work with for the occasion.
it's probably fine to add a caveat to this function to say that input data must be integers. than we cast float64 to uint32.
that formula is interesting. i don't quite understand why they add `2^width` to it, that seems to just cycle around to the same number. seems like the rate formula works just fine even with overflowed data, without adjustment, see
https://play.golang.org/p/a-5lEGXWs2 for example

**Comment by guillaumeautran** [comment]
I'm starting to appreciate GO more and more...
Looks like overflow operations are taken into consideration in the language itself: https://play.golang.org/p/_wAje5h2Jp
