### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by joemiller** [graphite-ng/carbon-relay-ng#264]
Subtle nudge / question - is there an ETA on the next release (0.9.5?) or anything I could do to help?

commits since last release - https://github.com/graphite-ng/carbon-relay-ng/compare/v0.9.4...master from a glance it looks like a new feature, a default change, a bug fix (issue #64), and some build infrastructure refactoring.

I am not super well versed in the ways of the semver but I think an 0.10.x bump could be warranted because a new feature (google pubsub support) was introduced.

**Comment by Dieterbe** [comment]
good idea. let's get #263 in and cut a new release

**Comment by guillaumeautran** [comment]
Could https://github.com/graphite-ng/carbon-relay-ng/pull/251 get reviewed and included in the next release?

**Comment by Mexx77** [comment]
Could https://github.com/graphite-ng/carbon-relay-ng/pull/261 and https://github.com/graphite-ng/carbon-relay-ng/pull/265 please be reviewed and included in the next release?

**Comment by bzed** [comment]
And the fix for #222 ....

**Comment by Dieterbe** [comment]
@bzed for that one I created a PR with fix and want someone to confirm it works before merging

in general folks, I know some of your PR's take a while to get reviewed and merged, it's because I'm busy with higher priority projects and paying customers. but i try to occasionally carve out some time for helping out the community in general.
You can help me move this faster by helping out with the reviewing process, by voting on issues/PR's, or if you get a GrafanaLabs subscription then I can also give your carbon-relay-ng issues high priority.

If anyone has suggestions on how to improve the collaborative model, I'm all ears.  E.g. if anyone is interested in co-maintaining for example.

**Comment by Mexx77** [comment]
My company recently bought a subscription on grafana.com (user ottode). Let me know if I can help any further. Feeling a little too fresh in the project for maintaining right now.

**Comment by Dieterbe** [comment]
@bzed 

> And the fix for #222 ....

there is no fix yet. as I pointed out in your PR, the proposed code has issues. and apparently my PR doesn't work either. if we don't have a fix soon it'll go into the next release.

**Comment by Dieterbe** [comment]
https://github.com/graphite-ng/carbon-relay-ng/releases/tag/0.10.0 new release is out !
