### ISSUE TITLE
Can't load package

### ISSUE THREAD

**Issue by mdzidic** [graphite-ng/carbon-relay-ng#352]
Hello,

I tried manual install of carbon-relay-ng from [INSTALL](https://github.com/graphite-ng/carbon-relay-ng/blob/master/docs/installation-building.md) and it fails.

I'm getting this error message:
```
# go get -d github.com/graphite-ng/carbon-relay-ng
can't load package: package github.com/graphite-ng/carbon-relay-ng: no Go files in /home/mdzidic/go/src/github.com/graphite-ng/carbon-relay-ng
```

**Comment by dr3amville** [comment]
+1 Not sure how to build this with the given instructions, get the same error as @mdzidic

**Comment by Dieterbe** [comment]
I'm afk right now but try adding '/cmd/carbon-relay-ng' to the URL

**Comment by dr3amville** [comment]
@Dieterbe I was actually able to get it to build a few minutes after by running the following:
`go get -u github.com/graphite-ng/carbon-relay-ng/...`

**Comment by Dieterbe** [comment]
looking into it more, 
```
# go get -d github.com/graphite-ng/carbon-relay-ng
can't load package: package github.com/graphite-ng/carbon-relay-ng: no Go files in /home/mdzidic/go/src/github.com/graphite-ng/carbon-relay-ng
```
this is actually expected.it complains because it can't install the binary, but it still downloads the repo.
the commands afterwards would allow to build. but i see how it is confusing.

anyway, i'm clearing up the docs. see the PR linked below, let me know if you like the new instructions.
