### ISSUE TITLE
Please clarify 'zero-downtime restarts'

### ISSUE THREAD

**Issue by tbielawa** [graphite-ng/carbon-relay-ng#60]
I understand from the README that "[carbon-relay-ng] can be restarted without dropping packets (needs testing)" but I am unclear on some things. Could you perhaps assist?
- Exactly how does this zero-downtime restart work? Obviously you're not describing a 'service carbonrelayng restart' type scenario.
- The README says this needs further testing, can you describe how to test this functionality?

Thanks!

**Comment by Dieterbe** [comment]
for this we use https://github.com/rcrowley/goagain
according to the docs we should just be able to send `SIGUSR2` to carbon-relay-ng and it'll restart without downtime.  it's been a while since i tried it, I presume carbon-relay-ng would need some work to make it work properly again (like flush all in memory buffers before quitting)

**Comment by Dieterbe** [comment]
this feature was removed.
see https://github.com/graphite-ng/carbon-relay-ng/releases/tag/v0.8 for details.
thanks
