### ISSUE TITLE
same endpoint addresses with spooling -> overlapping spool names cause spool issues

### ISSUE THREAD

**Issue by Dieterbe** [graphite-ng/carbon-relay-ng#64]
if you have the same address multiple times as endpoint (in the same or different routes), those are each an endpoint and conn but will use a spool file with the same name, which will conflict and cause all kinds of issues. like

```
2015/04/17 15:08:44 ERROR: diskqueue(spool_localhost_2005) failed to sync - rename spool/spool_localhost_2005.diskqueue.meta.dat.tmp spool/spool_localhost_2005.diskqueue.meta.dat: no such file or directory
```

long term, might want to use the same conn and spool for these multiple endpoints, but this would require more coordination logic. short term, we should just name them better, somehow.

**Comment by dkinon** [comment]
I am seeing this same issue.  You mention that the short term solution is to "name them better", can you expand on that?  Would I need to use different ports for each or maybe different names in /etc/hosts?

**Comment by Dieterbe** [comment]
yes, the workaround is making sure that all your combinations of tcp-addr:port of routes are unique, because that's what's used to generate the spool filenames.

**Comment by mrh666** [comment]
Hi @Dieterbe , is there is bugfix for spooling issue in 0.8 version?

**Comment by Dieterbe** [comment]
no sorry

**Comment by maggnus** [comment]
+1

**Comment by scrichar** [comment]
+1

**Comment by scrichar** [comment]
hey @Dieterbe,  what do you think the chances are that https://github.com/graphite-ng/carbon-relay-ng/pull/258 would be looked at / merged in to a new release ? I have forked the repo built carbon and have tested locally in our environments. Our issues was that without this fix we had to use regex's instead of a bunch of different routes with the same destination using prefix's. This caused a significantly large performance hit. With these changes we can both spool, and not take that performance hit...

**Comment by Dieterbe** [comment]
your pr looks pretty good. with a bit more followup I think we can merge your fix.

**Comment by Dieterbe** [comment]
ok folks, @scrichar made a nice PR that includes the routeName into the key for the destination. so now spool files, metrics, and log entries are all unique instead of colliding! just choose an appropriate route name :) thanks @scrichar !
